### PR TITLE
Fix exception with clearing rubble off map

### PR DESCRIPTION
**Pull request by axc**
Fixes https://github.com/battlecode/battlecode-server/issues/193

No delays are accumulated nor are signals sent to the client when an attempt is made to clear rubble off map or on a tile with no rubble.

### CODE REVIEW

**Comment by kazimuth** [comment]
Shouldn't it throw an exception?

**Comment by axc** [comment]
The current documentation says that "nothing will happen" if you try to clear off map, so we could either throw an exception or keep it consistent with the docs.

**Comment by kazimuth** [comment]
I would throw an exception, I think it'll help competitors catch bugs.

**Comment by axc** [comment]
Updated

**Pull request merged**
