### PR TITLE
RobotController changes

### PR DESCRIPTION
**Pull request by nmccoy**
Fixes some bugs / adds some features. See commit messages for issues referenced.

### CODE REVIEW

**Comment by axc** [comment]
Mind adding tests?

**Comment by nmccoy** [comment]
Whoops, definitely meant to do that. Adding tests now.

**Comment by nmccoy** [comment]
Should be good now

**Comment by axc** [comment]
Sorry one last thing. mind testing senseNearbyRobots() while you're at it? with infinite radius to make sure it doesn't sense all allied units

**Comment by axc** [comment]
I added tests to make sure senseNearbyRobots() also works. @kazimuth @nmccoy

**Pull request merged**
