### PR TITLE
Enable running multiple games in sequence

### PR DESCRIPTION
**Pull request by kazimuth**
Groundwork for scrimmage speed-ups.

Also allows multiple teams with the same way to be loaded from different jars, but there's no way to actually do that yet.

### CODE REVIEW

**Comment by kazimuth** [comment]
Oh yeah, it also gets rid of `Match`, since it was really just part of `Server` anyway.

**Comment by kazimuth** [comment]
NOT ready to merge.

**Comment by kazimuth** [comment]
Okay, now it should be ready to merge.

**Comment by axc** [comment]
Good to merge after fixing conflicts.

**Pull request merged**
